name: Run markdowner.py on all markdown files and see if there are changes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checks-out repository
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Run markdowner.py to (hopefully not) edit markdown files
      run: |
        find . -name '*.markdown' -type f -exec python3 .github/workflows/markdowner.py {} all \; | tee output.log
    - name: Check output.log file for warnings
      run: |
        ! grep WARNING output.log
    - name: Check if there are changes
      run: |
        git diff --exit-code
